version: '3.9'

services:
  database:
    container_name: musketgeeks_db
    image: postgres

    restart: always

    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}

    ports:
      - ${DATABASE_PORT}:5432
